### ISSUE TITLE
Extend Markdown Export

### ISSUE THREAD

**Issue by Feliix42** [tdolist/tdo#20]
The user should be able to decide, whether he wants to export all todos or just the ones that haven't been marked as done yet. (Or maybe just a certain list?)

- [x] sorted export
- [x] decide list to export
- [x] just undone/ all (/just done?)

**Comment by h4llow3En** [comment]
Also the output should be sorted

**Comment by h4llow3En** [comment]
Are you sure we should implement the function you can export only the undone or all? I think this would blow off the input. E.g. if you want all of some lists you would have to start tdo with
> tdo export /Path/where/to/export all list1 list2 list3

I think that would be a little to much an not user-friendly

**Comment by h4llow3En** [comment]
would blow of, close
