### ISSUE TITLE
Create github issues from local dir

### ISSUE THREAD

**Issue by kiliankoe** [tdolist/tdo#7]
So I saw that #2 works, which is pretty cool. Is there a way to use tdo to create issues in a current repo's remote?

Say something like

```
$ cd my-repo
$ tdo add 'this is a new issue'
```

and have tdo figure out the github remote from the current dir's .gitconfig and remote.

That'd be sweet.

**Comment by Feliix42** [comment]
This sounds more like you are looking for an actual Github CLI, which is a little bit outside the scope of this application. 😛

**Comment by h4llow3En** [comment]
the command would be 
```
tdo github 'this is a new issue'
```
or 
```
tdo github 'this is a new issue' 'with a body as a description'
```

**Comment by h4llow3En** [comment]
but this is an optional feature 😛 Maybe this could be implemented... with a PR? ◀️:octocat:❓

:trollface:
